# Generated by Django 3.2.8 on 2021-10-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='activate',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=120),
        ),
    ]
